export interface Arcana {
  n: number;
  slug: string;
  ru: string;
  keyword: string;
  plus: string;
  minus: string;
  task: string;
  en: { name: string; keyword: string; plus: string; minus: string; task: string };
}

export const ARCANA: Arcana[] = [
  { n: 1, slug: "mag", ru: "Маг", keyword: "воля и начало", plus: "Энергия первопроходца: вы умеете превращать идею в действие быстрее других, находите нестандартные ходы и заражаете уверенностью. Сильны в переговорах, запуске проектов, самопрезентации.", minus: "В минусе воля превращается в манипуляцию и распыление: десятки начатых дел без завершения, обещания «на кураже», игра на слабостях других.", task: "Научиться доводить начатое до результата и использовать дар убеждения ради честных целей.", en: { name: "The Magician", keyword: "will and initiative", plus: "A trailblazer's energy: you turn ideas into action faster than others, find unconventional moves and radiate conviction. Strong in negotiation, launches and self-presentation.", minus: "In shadow, will becomes manipulation and scatter: dozens of unfinished starts and promises made on a high.", task: "Learn to finish what you start and use your gift of persuasion for honest ends." } },
  { n: 2, slug: "zhritsa", ru: "Жрица", keyword: "знание и интуиция", plus: "Глубокая интуиция и тяга к знаниям: вы считываете скрытые мотивы, умеете учиться и учить, храните чужие тайны. Отличный наставник, исследователь, аналитик.", minus: "В минусе — закрытость, страх проявляться, накопление знаний «в стол», холодность в близких отношениях.", task: "Делиться знанием, а не прятать его; доверять интуиции и говорить о чувствах вслух.", en: { name: "The High Priestess", keyword: "knowledge and intuition", plus: "Deep intuition and a pull toward knowledge: you read hidden motives, learn and teach with ease, and keep confidences. A natural mentor, researcher, analyst.", minus: "In shadow \u2014 withdrawal, fear of being seen, knowledge hoarded 'for the drawer', coldness in close relationships.", task: "Share what you know instead of hiding it; trust your intuition and say feelings out loud." } },
  { n: 3, slug: "imperatritsa", ru: "Императрица", keyword: "изобилие и созидание", plus: "Природная способность взращивать: проекты, отношения, красоту вокруг. Щедрость, вкус, умение создавать уют и материальный достаток.", minus: "В минусе — гиперопека, растворение в других, заедание эмоций, лень и застой в комфорте.", task: "Созидать без самопожертвования: заботясь о других, не забывать наполнять себя.", en: { name: "The Empress", keyword: "abundance and creation", plus: "A born nurturer: you grow projects, relationships and beauty around you. Generosity, taste, a gift for comfort and material well-being.", minus: "In shadow \u2014 overprotection, dissolving into others, comfort-eating emotions, stagnation in coziness.", task: "Create without self-sacrifice: while caring for others, keep refilling yourself." } },
  { n: 4, slug: "imperator", ru: "Император", keyword: "структура и власть", plus: "Талант руководителя: системное мышление, ответственность, умение выстраивать порядок из хаоса и защищать своих. Люди идут за вами.", minus: "В минусе — авторитарность, контроль каждого шага, жёсткость к близким, работа ради статуса.", task: "Управлять, опираясь на уважение, а не страх; позволить другим ошибаться.", en: { name: "The Emperor", keyword: "structure and power", plus: "A leader's talent: systems thinking, responsibility, the ability to build order out of chaos and protect your people.", minus: "In shadow \u2014 authoritarian control, harshness with loved ones, working for status alone.", task: "Lead through respect rather than fear; let others make their own mistakes." } },
  { n: 5, slug: "ierofant", ru: "Иерофант", keyword: "традиция и наставничество", plus: "Мудрость учителя: вы соединяете поколения и смыслы, умеете объяснять сложное просто, создаёте вокруг себя сообщество и правила, которые работают.", minus: "В минусе — догматизм, «я знаю, как правильно», навязывание чужих сценариев, страх нового.", task: "Передавать опыт, оставляя другим свободу выбора; обновлять собственные убеждения.", en: { name: "The Hierophant", keyword: "tradition and mentorship", plus: "A teacher's wisdom: you connect generations and meanings, explain the complex simply, and build communities with rules that work.", minus: "In shadow \u2014 dogmatism, 'I know what's right', imposing scripts on others, fear of the new.", task: "Pass on experience while leaving others free to choose; keep updating your own beliefs." } },
  { n: 6, slug: "vlyublennye", ru: "Влюблённые", keyword: "выбор и любовь", plus: "Дар строить союзы: партнёрства, дружбу, любовь. Обаяние, эстетика, способность видеть красоту в людях и мирить противоположности.", minus: "В минусе — вечные метания между вариантами, зависимость от отношений, выбор «чтобы никого не обидеть».", task: "Научиться выбирать сердцем и брать ответственность за выбор, не перекладывая его на партнёра.", en: { name: "The Lovers", keyword: "choice and love", plus: "A gift for building unions: partnership, friendship, love. Charm, aesthetics, the ability to reconcile opposites.", minus: "In shadow \u2014 endless wavering between options, dependence on relationships, choosing 'so nobody gets hurt'.", task: "Learn to choose with your heart and own the choice instead of handing it to a partner." } },
  { n: 7, slug: "kolesnitsa", ru: "Колесница", keyword: "движение и победа", plus: "Энергия прорыва: скорость, целеустремлённость, умение управлять сразу несколькими процессами. Вы созданы для динамики, дорог и амбициозных целей.", minus: "В минусе — гонка ради гонки, агрессия за рулём жизни, выгорание, неумение останавливаться.", task: "Направлять мощь в одну цель за раз и помнить, куда именно вы едете.", en: { name: "The Chariot", keyword: "motion and victory", plus: "Breakthrough energy: speed, focus, the ability to steer several processes at once. Built for momentum, roads and ambitious goals.", minus: "In shadow \u2014 racing for its own sake, burnout, not knowing how to stop.", task: "Aim your power at one goal at a time \u2014 and remember where you're actually going." } },
  { n: 8, slug: "spravedlivost", ru: "Справедливость", keyword: "закон и равновесие", plus: "Обострённое чувство честности: вы умеете взвешивать, договариваться, наводить порядок в документах, финансах и отношениях. Вам доверяют арбитраж.", minus: "В минусе — сведение счётов, «зуб за зуб», бюрократическая жёсткость, суд над собой строже любого суда.", task: "Судить с милосердием — начиная с самого себя.", en: { name: "Justice", keyword: "law and balance", plus: "A sharpened sense of fairness: you weigh, negotiate, and bring order to documents, finances and relationships. People trust you as an arbiter.", minus: "In shadow \u2014 score-settling, bureaucratic rigidity, judging yourself harder than any court.", task: "Judge with mercy \u2014 starting with yourself." } },
  { n: 9, slug: "otshelnik", ru: "Отшельник", keyword: "мудрость и путь к себе", plus: "Глубина и самодостаточность: вы умеете быть наедине с собой, видите суть вещей, становитесь проводником для тех, кто ищет ответы.", minus: "В минусе — изоляция, отчуждённость, «меня никто не понимает», уход от жизни в философию.", task: "Выносить найденный внутри свет к людям, а не прятаться с ним в пещере.", en: { name: "The Hermit", keyword: "wisdom and the inner path", plus: "Depth and self-sufficiency: you can be alone with yourself, see the essence of things, and guide those who seek answers.", minus: "In shadow \u2014 isolation, 'nobody understands me', escaping life into philosophy.", task: "Bring the light you find within out to people \u2014 don't hide with it in a cave." } },
  { n: 10, slug: "koleso-fortuny", ru: "Колесо Фортуны", keyword: "удача и циклы", plus: "Врождённая удачливость и чутьё на возможности: вы оказываетесь в нужное время в нужном месте, легко проходите перемены и умеете начинать заново.", minus: "В минусе — ставка на «авось», азарт, хождение по кругу одних и тех же граблей.", task: "Заметить повторяющиеся циклы своей жизни и осознанно выйти на новый виток.", en: { name: "Wheel of Fortune", keyword: "luck and cycles", plus: "Innate luck and a nose for opportunity: right place, right time, easy restarts after change.", minus: "In shadow \u2014 betting on chance, thrill-seeking, circling the same rakes again and again.", task: "Notice your life's repeating cycles and consciously step onto a new turn of the spiral." } },
  { n: 11, slug: "sila", ru: "Сила", keyword: "энергия и страсть", plus: "Огромный запас жизненной силы: выносливость, магнетизм, способность «вывозить» то, от чего другие ломаются. Умеете укрощать и свои, и чужие стихии.", minus: "В минусе — подавление слабых, вспышки гнева, сила во вред себе: перегрузки, риск, изматывание тела.", task: "Приручить собственную мощь: мягкость — высшая форма силы.", en: { name: "Strength", keyword: "energy and passion", plus: "A huge reserve of vitality: endurance, magnetism, the capacity to carry what breaks others. You tame storms \u2014 your own and other people's.", minus: "In shadow \u2014 domineering the weak, flashes of anger, strength turned against your own body.", task: "Tame your own power: gentleness is strength's highest form." } },
  { n: 12, slug: "poveshennyy", ru: "Повешенный", keyword: "иной взгляд и жертва", plus: "Умение видеть мир под непривычным углом: креативность, нестандартные решения, способность отпускать и переосмыслять. Духовная гибкость.", minus: "В минусе — позиция жертвы, «подвисание» в решениях, самопожертвование без благодарности, ожидание спасателя.", task: "Сместить фокус с «за что мне это» на «для чего», и слезть с креста добровольно.", en: { name: "The Hanged Man", keyword: "a different angle and sacrifice", plus: "Seeing the world from an unusual angle: creativity, unconventional solutions, the ability to let go and reframe.", minus: "In shadow \u2014 the victim position, stalled decisions, sacrifice without gratitude, waiting for a rescuer.", task: "Shift from 'why me' to 'what for' \u2014 and climb down from the cross voluntarily." } },
  { n: 13, slug: "smert", ru: "Смерть", keyword: "трансформация", plus: "Мастер перерождений: вы умеете завершать отжившее и начинать с чистого листа, помогаете другим проходить кризисы. После каждого падения становитесь сильнее.", minus: "В минусе — страх перемен, цепляние за прошлое, разрушение ради разрушения, драматизация.", task: "Полюбить завершения: каждое из них освобождает место новому.", en: { name: "Death", keyword: "transformation", plus: "A master of rebirth: you close finished chapters and start clean, helping others through crises. Every fall makes you stronger.", minus: "In shadow \u2014 fear of change, clinging to the past, destruction for its own sake.", task: "Learn to love endings: each one clears space for the new." } },
  { n: 14, slug: "umerennost", ru: "Умеренность", keyword: "баланс и исцеление", plus: "Дар гармонизации: вы соединяете несоединимое, умеете лечить словом и присутствием, находите золотую середину в конфликте.", minus: "В минусе — «тише воды», избегание конфликтов любой ценой, пресная жизнь без страсти, вечное откладывание.", task: "Балансировать, не растворяясь: у гармонии тоже должен быть характер.", en: { name: "Temperance", keyword: "balance and healing", plus: "A harmonizing gift: you join the unjoinable, heal with words and presence, and find the golden mean in conflict.", minus: "In shadow \u2014 avoiding conflict at any cost, a flavorless life without passion, eternal postponement.", task: "Balance without dissolving: harmony needs a backbone too." } },
  { n: 15, slug: "diavol", ru: "Дьявол", keyword: "материя и искушение", plus: "Мощная энергия материального успеха: харизма, сексуальность, деловая хватка, умение видеть чужие желания и монетизировать таланты.", minus: "В минусе — зависимости (деньги, азарт, отношения), манипуляции, жизнь в погоне за удовольствием без смысла.", task: "Владеть материей, не позволяя ей владеть собой.", en: { name: "The Devil", keyword: "matter and temptation", plus: "Powerful material drive: charisma, magnetism, business grip, the ability to see desires and monetize talent.", minus: "In shadow \u2014 addictions (money, thrill, relationships), manipulation, pleasure-chasing without meaning.", task: "Master matter without letting it master you." } },
  { n: 16, slug: "bashnya", ru: "Башня", keyword: "разрушение иллюзий", plus: "Способность рушить отжившие конструкции и строить заново: антикризисный талант, смелость правды, энергия обновления системы.", minus: "В минусе — жизнь от кризиса к кризису, разрушение собственными руками того, что строилось годами, гордыня.", task: "Разбирать старое осознанно и по кирпичику — не дожидаясь молнии.", en: { name: "The Tower", keyword: "shattered illusions", plus: "The power to demolish outlived structures and rebuild: crisis-management talent, courage to speak truth, system-renewal energy.", minus: "In shadow \u2014 living from crisis to crisis, wrecking with your own hands what took years to build.", task: "Dismantle the old consciously, brick by brick \u2014 don't wait for lightning." } },
  { n: 17, slug: "zvezda", ru: "Звезда", keyword: "надежда и признание", plus: "Талант вдохновлять: вы созданы быть видимым — сцена, творчество, публичность. Дарите людям надежду и веру в лучшее самим фактом своего примера.", minus: "В минусе — зависимость от чужого одобрения, звёздная болезнь либо, наоборот, страх проявиться.", task: "Светить из внутреннего источника, а не ради аплодисментов.", en: { name: "The Star", keyword: "hope and recognition", plus: "A talent for inspiring: you are made to be visible \u2014 stage, art, public life. Your example alone gives people hope.", minus: "In shadow \u2014 dependence on approval, stardom sickness or, conversely, fear of being seen.", task: "Shine from an inner source, not for applause." } },
  { n: 18, slug: "luna", ru: "Луна", keyword: "интуиция и подсознание", plus: "Тончайшая чувствительность: развитая интуиция, богатое воображение, эмпатия, магнетическое обаяние тайны. Сильны в психологии и творчестве.", minus: "В минусе — страхи и тревоги, иллюзии, самообман, эмоциональные качели, зависимость от лунных циклов.", task: "Сделать интуицию союзником, отделив её голос от голоса страха.", en: { name: "The Moon", keyword: "intuition and the subconscious", plus: "Finest sensitivity: developed intuition, rich imagination, empathy, the magnetic charm of mystery. Strong in psychology and art.", minus: "In shadow \u2014 fears and anxieties, illusions, self-deception, emotional swings.", task: "Make intuition your ally by separating its voice from the voice of fear." } },
  { n: 19, slug: "solntse", ru: "Солнце", keyword: "успех и радость", plus: "Солнечная витальность: оптимизм, щедрость, детская искренность и взрослая результативность. Вы согреваете команды и семьи, притягиваете успех.", minus: "В минусе — эгоцентризм, «я — центр вселенной», выгорание от желания светить всем сразу, инфантильность.", task: "Светить, не выжигая себя: радость — топливо, а не обязанность.", en: { name: "The Sun", keyword: "success and joy", plus: "Solar vitality: optimism, generosity, a child's sincerity with an adult's results. You warm teams and families and attract success.", minus: "In shadow \u2014 egocentrism, burnout from trying to shine on everyone at once.", task: "Shine without burning out: joy is fuel, not an obligation." } },
  { n: 20, slug: "sud", ru: "Суд", keyword: "предназначение рода", plus: "Глубокая связь с родом и умение слышать призвание: вы способны исцелять семейные сценарии, объединять близких, слышать «зов» и следовать ему.", minus: "В минусе — груз чужих ожиданий, жизнь по родительскому сценарию, вина перед семьёй, откладывание собственной жизни.", task: "Взять из рода силу, а сценарии — переписать под себя.", en: { name: "Judgement", keyword: "calling and renewal", plus: "The energy of awakening: you hear your calling, help others rise to a new level, and close karmic chapters for the whole family line.", minus: "In shadow \u2014 endless self-judgement, living by others' verdicts, fear of the final decision.", task: "Answer your calling \u2014 it is louder than any outside judgement." } },
  { n: 21, slug: "mir", ru: "Мир", keyword: "целостность и масштаб", plus: "Энергия больших пространств: международные проекты, путешествия, умение объединять людей разных культур. Вы мыслите глобально и завершаете большие циклы.", minus: "В минусе — «нигде не дома», разбросанность по миру и по целям, страх завершений, вечное «почти получилось».", task: "Собрать свой мир воедино: масштаб начинается с внутренней целостности.", en: { name: "The World", keyword: "completion and harmony", plus: "The gift of wholeness: you finish big cycles, unite people and cultures, feel at home anywhere on Earth.", minus: "In shadow \u2014 fear of finishing, a suitcase-life without roots, dissolving in the world's noise.", task: "Complete what matters and let yourself receive the reward." } },
  { n: 22, slug: "shut", ru: "Шут", keyword: "свобода и доверие миру", plus: "Абсолютная лёгкость бытия: спонтанность, юмор, бесстрашие новичка, умение начинать с нуля в любом возрасте. Вы напоминаете миру, что жизнь — игра.", minus: "В минусе — безответственность, вечный подросток, шаг в пропасть на спор, неумение держать обязательства.", task: "Сохранить лёгкость, добавив к ней опору: свобода — это ответственность, которой не тяжело.", en: { name: "The Fool", keyword: "freedom and beginnings", plus: "Absolute openness to life: lightness, spontaneity, the courage to start from zero and trust the road.", minus: "In shadow \u2014 irresponsibility, eternal adolescence, jumping off before the result.", task: "Keep the lightness \u2014 and add direction: freedom loves the brave, not the scattered." } },
];

export function arcanaByNumber(n: number): Arcana {
  const idx = ((n - 1) % 22 + 22) % 22;
  return ARCANA[idx];
}

export function arcanaBySlug(slug: string): Arcana | undefined {
  return ARCANA.find((a) => a.slug === slug);
}

/** Редукция числа до аркана (1–22). */
export function reduceToArcana(n: number): number {
  let x = n;
  while (x > 22) {
    x = String(x)
      .split("")
      .reduce((s, d) => s + Number(d), 0);
  }
  return x === 0 ? 22 : x;
}

export interface MatrixResult {
  day: number; // личный аркан (день)
  month: number;
  year: number;
  core: number; // аркан судьбы (сумма трёх)
  comfort: number; // зона комфорта (день + core)
}

/** Базовый расчёт Матрицы судьбы по дате рождения. */
export function calcMatrix(d: number, m: number, y: number): MatrixResult {
  const day = reduceToArcana(d);
  const month = reduceToArcana(m);
  const year = reduceToArcana(
    String(y).split("").reduce((s, x) => s + Number(x), 0),
  );
  const core = reduceToArcana(day + month + year);
  const comfort = reduceToArcana(day + core);
  return { day, month, year, core, comfort };
}
