import type { Metadata } from "next";
import Link from "next/link";
import CTA from "@/components/CTA";
import Reveal from "@/components/Reveal";
import NatalWheel from "@/components/NatalWheel";
import FAQ from "@/components/FAQ";
import { deepLink, pageOg } from "@/lib/site";

export const metadata: Metadata = {
  title: "Free Birth Chart with NASA-grade Precision — Astro Orb AI Astrologer",
  description:
    "Your personal AI astrologer in Telegram: birth chart via Swiss Ephemeris, destiny matrix, compatibility and daily horoscopes. Free calculation in 2 minutes, no app install.",
  alternates: { canonical: "/en", languages: { ru: "/", en: "/en", "x-default": "/" } },
  openGraph: pageOg("/en", "en"),
};

const FEATURES = [
  { title: "Birth chart", text: "10 planets, houses, aspects — and a living reading written for you, not a template.", cta: "features_natal", href: "/en/natal-chart", anchor: "More about the birth chart" },
  { title: "Compatibility", text: "Synastry from two full charts: love, money, everyday life, crisis points.", cta: "features_compat", href: "/en/compatibility", anchor: "More about compatibility" },
  { title: "Destiny matrix", text: "22 arcana from your birth date: calling, family line, karmic lessons.", cta: "features_matrix", href: "/en/matrix", anchor: "More about the matrix" },
  { title: "Solar Return", text: "A forecast for your personal year — from birthday to birthday, timed to the exact solar return.", cta: "features_solar", href: "/en/solar-return", anchor: "More about Solar Return" },
  { title: "Horoscopes", text: "Daily, weekly and monthly forecasts mapped onto the houses of your own chart.", cta: "features_dates", href: "/en/horoscope", anchor: "More about horoscopes" },
  { title: "Oracle", text: "Ask anything — the AI answers from your chart, not from generic phrases.", cta: "features_oracle", href: "/en/about", anchor: "More about Oracle" },
];

const HOME_FAQ = [
  { q: "Is the birth chart really free?", a: "Yes. The chart with the wheel, Sun, Moon and ascendant is calculated free right on this site, no sign-up. The full AI reading of all planets, houses and aspects lives in the Astro Orb Mini App in Telegram." },
  { q: "How accurate are the calculations?", a: "Planetary positions come from Swiss Ephemeris — the professional standard built on NASA JPL ephemerides, accurate to fractions of an arc second. Interpretations are generated by a modern language model from your exact configuration." },
  { q: "Do I need to install anything?", a: "No. Astro Orb runs as a Mini App inside Telegram — it opens like a chat, works on any phone and remembers your charts." },
  { q: "What if I don't know my birth time?", a: "You still get the Sun, Moon and all planets in signs. The ascendant and house grid need a time — in the Mini App you can refine it from life events (rectification)." },
  { q: "How much does the full version cost?", a: "The chart is free forever. Subscriptions unlock full readings: Standard from 99 ₽/month, Premium from 179 ₽/month (billed yearly) — payable by card, TON or Telegram Stars worldwide." },
];

export default function EnHome() {
  return (
    <>
      <section className="mx-auto grid max-w-6xl items-center gap-12 px-4 pt-10 lg:grid-cols-2">
        <div>
          <p className="eyebrow">AI astrologer in Telegram</p>
          <h1 className="mt-5 font-display text-4xl leading-[1.12] md:text-5xl">
            Your birth chart with <span className="grad-text">NASA-grade precision</span> — free
          </h1>
          <p className="mt-5 max-w-xl text-lg text-muted">
            Enter your birth date — get the chart wheel, your Sun, Moon and ascendant right on this
            page. The full AI reading is waiting in the Mini App.
          </p>
          <div className="mt-8 flex flex-wrap items-center gap-4">
            <CTA page="en_home" cta="hero">Build my chart free</CTA>
            <Link href="/en/natal-chart" className="text-sm text-iris hover:underline">
              Try the calculator →
            </Link>
          </div>
          <p className="mt-5 text-sm text-muted">Free · NASA JPL precision · Result in a minute</p>
        </div>
        <div className="flex justify-center">
          <NatalWheel slowSpin size={420} />
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-4 py-24">
        <Reveal>
          <h2 className="max-w-2xl font-display text-3xl md:text-4xl">Six tools in one bot</h2>
        </Reveal>
        <div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {FEATURES.map((f, i) => (
            <Reveal key={f.title} delay={(i % 3) * 70}>
              <div className="flex h-full flex-col rounded-2xl border border-hairline bg-surface p-6 transition-[border-color,transform] duration-300 ease-out-strong hover:-translate-y-0.5 hover:border-iris/40">
                <h3 className="font-display text-lg">{f.title}</h3>
                <p className="mt-2 flex-1 text-sm leading-relaxed text-muted">{f.text}</p>
                <div className="mt-5 flex items-center justify-between text-sm">
                  <Link href={f.href} className="text-muted transition-colors hover:text-ink">
                    {f.anchor}
                  </Link>
                  <a href={deepLink("en_home", f.cta)} className="text-iris hover:underline">
                    Try ↗
                  </a>
                </div>
              </div>
            </Reveal>
          ))}
        </div>
      </section>

      <section className="mx-auto max-w-3xl px-4 py-24 text-center">
        <Reveal>
          <h2 className="font-display text-3xl md:text-4xl">
            Start with the chart — <span className="grad-text">it's free</span>
          </h2>
          <p className="mx-auto mt-4 max-w-xl text-muted">
            Two minutes from birth date to a living reading. No sign-up on the site, no app install.
          </p>
          <div className="mt-8 flex justify-center">
            <CTA page="en_home" cta="final">Open Astro Orb</CTA>
          </div>
        </Reveal>
      </section>

      <FAQ items={HOME_FAQ} title="FAQ" />
    </>
  );
}
